languageCode = "en-us"
title = "CC Ozkan"
baseurl = "//ozkan.cc/"
publishDir = "docs"
themesDir = "themes"
theme = "aerial"

[params]
  name = "C Cagri Ozkan"
  about = ""
  copyright = ""
  #Disable the scrolling background by entering any string for bg_scroll. Enable by leaving bg_scroll empty.
  bg_scroll = "42"




[[params.social]]
  medium = "Github"
  icon = "github"
  link = "https://github.com/ozkc"

[[params.social]]
  medium = "Email"
  icon = "envelope-o"
  link = "mailto:ozkancdev@gmail.com"
