baseurl = "/"
relativeurls = true

title = "CC Ozkan"
publishDir = "docs"
theme = "hugo-coder"

googleAnalytics = "UA-135899545-4"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "C Çağrı Özkan"
    description = "asdasdasd"
    keywords = "blog,developer,personal"
    info = ""
    avatarurl = "t.jpg"
    footercontent = "personal website yo!"

    dateformat = "January 2, 2006"

    hideCredits = true
    hideCopyright = false

    # Git Commit in Footer, uncomment the line below to enable it.
#    commit = "https://github.com/ozkc/ozkancc/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "light"

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
#    custom_css = []
    
    # Custom JS
 #   custom_js = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    target="_blank"
    url = "https://github.com/ozkc/"

[[params.social]]
    name = "Telegram"
    target="_blank"
    icon = "fab fa-telegram"
    weight = 2
    url = "https://t.me/cagrio"

[[params.social]]
    name = "Email"
    icon = "fa fa-envelope"
    weight = 3
    url = "mailto:mail@ozkan.cc"


[[menu.main]]
    name = "| Projects |"
    weight = 1
    url = "projects"

[[menu.main]]
    name = "| Blog |"
    weight = 3
    url = "blog"

[[menu.main]]
    name = "> rss"
    weight = 4
    url = "https://ozkan.cc/index.xml"
