
baseurl = "https://ozkc.github.io/ozkancc/"
relativeurls = false
#uglyurls = true
title = "CC Ozkan"
publishDir = "docs"
theme = "hugo-coder"

languagecode = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "C Çağrı Özkan"
    description = ""
    keywords = ""
    info = ""
    avatarurl = "dagcrop.jpg"
    footercontent = "personal website yo"
    dateformat = "2018"

    hideCredits = true
    hideCopyright = true

    rtl = false

    # Custom CSS
    custom_css = []

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/ozkc/"

[[params.social]]
    name = "Email"
    icon = "fa fa-at"
    weight = 2
    url = "mailto:ozkancdev@gmail.com"


[[menu.main]]
    name = "Projects"
    weight = 1
    url = "projects"
