
baseurl = "/"
#baseurl = "https://ozkc.github.io/ozkancc/"
relativeurls = true
#uglyurls = true
title = "CC Ozkan"
publishDir = "docs"
theme = "hugo-coder"

languagecode = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "C Çağrı Özkan"
    description = ""
    keywords = ""
    info = "developer, mechanical engineer"
    avatarurl = "t.jpg"
    footercontent = "personal website yo"
    dateformat = "2018"

    hideCredits = true
    hideCopyright = true

    rtl = false

    # Custom CSS

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/ozkc/"

[[params.social]]
    name = "Email"
    icon = "fa fa-at"
    weight = 2
    url = "mailto:mail@ozkan.cc"

[[menu.main]]
    name = "| Projects |"
    weight = 1
    url = "projects"

[[menu.main]]
    name = "| About me |"
    weight = 1
    url = "aboutme"
